### ISSUE TITLE
not working as drop-in replacement

### ISSUE THREAD

**Issue by edu-diez** [origamiofficial/docker-pihole-unbound#23]
## Details

Looking at the developer comments I understood that this image could work as a drop-in replacemente of chriscrowe's container. I replaced his image with this one in the compose file but the container keeps restarting. Should I create a new one from the ground up?

    piholeunb:
        container_name: piholeunb
        image: cbcrowe/pihole-unbound:latest
        ports:
            - "443:443/tcp"
            - "53:53/tcp"
            - "53:53/udp"
            - "80:80/tcp"
            # - 5335:5335/tcp # Uncomment to enable unbound access on local server
        environment:
            FTLCONF_LOCAL_IPV4: '192.168.0.24'
            TZ: '*******'
            WEBPASSWORD: '**********'
            REV_SERVER: 'true'
            REV_SERVER_TARGET: '192.168.0.1'
            REV_SERVER_DOMAIN: 'local'
            REV_SERVER_CIDR: '192.168.0.0/24'
            PIHOLE_DNS_: 127.0.0.1#5335 # Hardcoded to our Unbound server
            DNSSEC: 'false' # Enable DNSSEC
        volumes:
            - "./pihole/etc-pihole:/etc/pihole:rw"
            - "./pihole/etc-dnsmasq.d:/etc/dnsmasq.d:rw"
            - "./resolv.conf:/etc/resolv.conf"
        restart: unless-stopped

## Related Questions
- [x] I have searched this repository/Pi-hole official repository/Pi-hole forums for existing issues, questions and pull requests that look similar 

## General knowledge about the question

1. Environment data
  * Operating System: **Raspberry Pi OS Lite 64-bit** 
  * Hardware: Raspberry Pi 3B+
  * Kernel Architecture: aarch64 
  * Docker Install Info and version: Docker version 25.0.1, build 29cf629
    - Software source: official docker-ce 
    - Supplimentary Software: 
  * Hardware architecture: aarch64 
  * Docker Image Tag: lastest

**Comment by origamiofficial** [comment]
If you skip the issue template I can't help you.

**Comment by edu-diez** [comment]
@origamiofficial I skipped it because I made it as a question, not an issue. Mostly because I thought it was a fault on my side. Should I recreate it as an issue?

**Comment by origamiofficial** [comment]
Yes recreate with all details
