### ISSUE TITLE
Unbound does not start in development-v6 image

### ISSUE THREAD

**Issue by adman-c** [origamiofficial/docker-pihole-unbound#24]
This is a: Bug  

## Details with Docker log

When running the basic command for the `development-v6` branch, pihole launches fine (I can access the WebUI), but it does not appear that unbound installs properly. There is no DNS resolution when querying localhost:
```
user@docker5:~/docker$ dig @127.0.0.1 cnn.com
;; communications error to 127.0.0.1#53: timed out
;; communications error to 127.0.0.1#53: timed out
;; communications error to 127.0.0.1#53: timed out

; <<>> DiG 9.18.18-0ubuntu0.22.04.1-Ubuntu <<>> @127.0.0.1 cnn.com
; (1 server found)
;; global options: +cmd
;; no servers could be reached
```

 If I enter the container and attempt to run /opt/unbound/sbin/unbound I get the following errors:
```
a2c11b29f0ad:/# /opt/unbound/sbin/unbound
Error loading shared library libevent-2.1.so.7: No such file or directory (needed by /opt/unbound/sbin/unbound)
Error relocating /opt/unbound/sbin/unbound: event_get_version: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_set: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_base_free: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_assign: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_base_dispatch: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_base_get_method: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_del: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_add: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_base_set: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_base_new: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_base_loopexit: symbol not found
```

If I attempt to run /unbound.sh inside the container, I get the following similar errors:
```
a2c11b29f0ad:/# ./unbound.sh 
./unbound.sh: line 21: perl: command not found
Error loading shared library libevent-2.1.so.7: No such file or directory (needed by /opt/unbound/lib/libunbound.so.8)
Error relocating /opt/unbound/lib/libunbound.so.8: event_get_version: symbol not found
Error relocating /opt/unbound/lib/libunbound.so.8: event_set: symbol not found
Error relocating /opt/unbound/lib/libunbound.so.8: event_base_free: symbol not found
Error relocating /opt/unbound/lib/libunbound.so.8: event_base_dispatch: symbol not found
Error relocating /opt/unbound/lib/libunbound.so.8: event_base_get_method: symbol not found
Error relocating /opt/unbound/lib/libunbound.so.8: event_del: symbol not found
Error relocating /opt/unbound/lib/libunbound.so.8: event_add: symbol not found
Error relocating /opt/unbound/lib/libunbound.so.8: event_base_set: symbol not found
Error relocating /opt/unbound/lib/libunbound.so.8: event_base_new: symbol not found
Error relocating /opt/unbound/lib/libunbound.so.8: event_base_loopexit: symbol not found
Error loading shared library libevent-2.1.so.7: No such file or directory (needed by /opt/unbound/sbin/unbound)
Error relocating /opt/unbound/sbin/unbound: event_get_version: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_set: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_base_free: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_assign: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_base_dispatch: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_base_get_method: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_del: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_add: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_base_set: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_base_new: symbol not found
Error relocating /opt/unbound/sbin/unbound: event_base_loopexit: symbol not found
```

For whatever it's worth, I did notice that the `latest` image appears to take up about twice as much storage as the `development-v6` image--maybe the latter somehow does not include some necessary files?

## Related Issues
- [x ] I have searched this repository/Pi-hole official repository/Pi-hole forums for existing issues and pull requests that look similar 

Did not find any similar issues.

## How to reproduce the issue 

1. Environment data
  * Operating System: Ubuntu Server 22.04 QEMU VM
  * Hardware: AMD EPYC 7532 
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: 
    - Software source: official docker-ce 
    - Supplimentary Software: portainer 
  * Hardware architecture: x86
  * Docker Image Tag: development v6

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
docker run -d --name pihole-unbound \
  --name=pihole-unbound \
  -e TZ=America/Chicago  \
  -p 53:53/tcp -p 53:53/udp \
  -p 80:80/tcp `#Pi-hole web interface port` \
  -e FTLCONF_webserver_api_password=''  \
  --restart=always \
  rlabinc/pihole-unbound:development-v6
```
4. any additional info to help reproduce
This error persists whether I run with a docker-compose file or just run the basic command above. I have also tested on 2 different machines, one Intel and one AMD. 

## Upload the unbound log file
unbound.log is empty--It appears that unbound never successfully launches.
## These common fixes didn't work for my issue

- [ x] I have tried removing/destroying my container, and re-creating a new container
- [ x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ x] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have tried running official Pi-hole docker image to check if it works there

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.
The `latest` image when run using the following command works fine and resolves using unbound:
```
docker run -d --name pihole-unbound \
  --name=pihole-unbound \
  -e TZ=America/Chicago \
  -p 53:53/tcp -p 53:53/udp \
  -p 80:80/tcp `#Pi-hole web interface port` \
  -e WEBPASSWORD='' \
  --restart=always \
  rlabinc/pihole-unbound:latest 
```

**Comment by origamiofficial** [comment]
Support for the `development-v6` tag is temporarily paused along with auto build, as it needs some fixes but I'm not an expert in Alpine. If you can feel free to contribute and submit your PR.
