### ISSUE TITLE
Missing recent pihole with specific date tag

### ISSUE THREAD

**Issue by jhomen368** [origamiofficial/docker-pihole-unbound#25]
This is a:  Build issue

## Related Issues
- [X] I have searched this repository/Pi-hole official repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 
1. Environment data
  * Operating System: **Ubuntu** 
  * Hardware: N/A 
  * Kernel Architecture:  x86/amd64 
  * Docker Install Info and version: 
    - Software source: Kubernetes/RKE2 
    - Supplimentary Software: N/A 
  * Hardware architecture: x86  
  * Docker Image Tag: 

https://github.com/origamiofficial/docker-pihole-unbound/releases/tag/2024.02.0 has a release dated for 2024.02.0 that doesn't exist in the docker hub https://hub.docker.com/r/rlabinc/pihole-unbound/tags

latest version that I could fiind that had a specific date tag was rlabinc/pihole-unbound:20240108

**Comment by origamiofficial** [comment]
Fixed in afdc112a036f6a8c89eb5559dfea6e5bdd15ad9a
