### ISSUE TITLE
Broken link to the Unbound changelog in the releases

### ISSUE THREAD

**Issue by dmarcoux** [origamiofficial/docker-pihole-unbound#27]
At the time of writing, the latest release links to Unbound changelog with https://github.com/NLnetLabs/unbound/releases/tag/1.19.3 while it should instead be https://github.com/NLnetLabs/unbound/releases/tag/release-1.19.3

**Comment by origamiofficial** [comment]
Already fixed ffc5c13, wait for a manual push.
