### ISSUE TITLE
private-domain.conf not working

### ISSUE THREAD

**Issue by Aiki033** [origamiofficial/docker-pihole-unbound#32]
Hi,

not really a bug or issue but I was wondering if loading a custom private-domain.conf is different here. 

Pihole is working great the only thing that is not working is my private-domain.conf.

When using chriscrowe's pihole-unbound in 1 container, I bind /home/user/private-domain.conf:/etc/unbound/unbound.conf.d/private-domain.conf:rw to address the DNS Rebind protection of MyJdownloader and get a direct connection. Already tried restarting pihole container and jdownloader container.

Running on Orangepi 5 on Armbian Bookworm 

These common fixes didn't work for my issue
[ x] I have tried removing/destroying my container, and re-creating a new container
[ x] I have tried fresh volume data by backing up and moving/removing the old volume data
[  ] I have tried running the stock docker run example(s) in the readme (removing any customizations I added)
[  ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
[  ] I have tried running without my volume data mounts to eliminate volumes as the cause
[  ] I have tried running official Pi-hole docker image to check if it works there

**Comment by origamiofficial** [comment]
This container isn't chriscrowe's replacement, so things aren't exactly where you think of. Please read [Readme](https://github.com/origamiofficial/docker-pihole-unbound/blob/main/README.md) before opening a issue. Check below items:

https://github.com/origamiofficial/docker-pihole-unbound/tree/main?tab=readme-ov-file#parameters

https://github.com/origamiofficial/docker-pihole-unbound/tree/main/data/opt/unbound/etc/unbound
